version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g gatsby
      - run: ls
      - run: gatsby build
    # #   - run: |
    # #      docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
    # # # build the application image
    # #   - run: docker build -t $DOCKER_REGISTRY/app:latest .

    #  # deploy the image
    #   - run: docker push company/app:latest
    branches:
      only:
        - docker