version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
         docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PASS
    # build the application image
      - run: docker build -t $DOCKER_REGISTRY/app:latest .

     # deploy the image
      - run: docker push company/app:latest
    branches:
      only:
        - docker