import * as art from 'src/images/mix-art/';
import * as labels from 'src/images/mix-labels/';
// import rm001 from '../images/rm001.jpg';

const BASE_URL = 'https://roomhauscdnprd.blob.core.windows.net/mixes/';

export const mixes = [
  {
    id: 'MX001',
    art: art.MX001,
    label: labels.MX001,
    artist: 'Eddy Bauer',
    catalogueNumber: 'MX001',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx001-eddy-bauer',
    audioSourceURL: `${BASE_URL}MX001/MX001.m3u8`,
  },
  {
    id: 'MX002',
    art: art.MX002,
    label: labels.MX002,
    artist: '35mm',
    catalogueNumber: 'MX002',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx002-35mm',
    audioSourceURL: `${BASE_URL}MX002/MX002.m3u8`,
  },
  {
    id: 'MX003',
    art: art.MX003,
    label: labels.MX003,
    artist: 'Blackfoot Millie',
    catalogueNumber: 'MX003',
    soundcloud: 'https://soundcloud.com/room-haus/mx003-blackfoot-millie-live',
    audioSourceURL: `${BASE_URL}MX003/MX003.m3u8`,
  },
  {
    id: 'MX004',
    art: art.MX004,
    label: labels.MX004,
    artist: 'Iwan Thickett',
    name: 'MX004: Iwan Thickett',
    catalogueNumber: 'MX004',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx004-iwan-thickett',
    audioSourceURL: `${BASE_URL}MX004/MX004.m3u8`,
  },
  {
    id: 'MX005',
    art: art.MX005,
    label: labels.MX005,
    artist: 'AV',
    catalogueNumber: 'MX005',
    soundcloud: 'https://soundcloud.com/room-haus/mx005-av',
    audioSourceURL: `${BASE_URL}MX005/MX005.m3u8`,
  },
  {
    id: 'MX006',
    art: art.MX006,
    label: labels.MX006,
    catalogueNumber: 'MX006',
    artist: 'Articil',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx006-articil',
    audioSourceURL: `${BASE_URL}MX006/MX006.m3u8`,
  },
  {
    id: 'MX007',
    art: art.MX007,
    label: labels.MX007,
    artist: 'Wade Hammes',
    catalogueNumber: 'MX007',
    soundcloud: 'https://soundcloud.com/room-haus/mx007-wade-hammes',
    audioSourceURL: `${BASE_URL}MX007/MX007.m3u8`,
  },
  {
    id: 'MX008',
    art: art.MX008,
    label: labels.MX008,
    artist: 'Big Chain',
    catalogueNumber: 'MX008',
    soundcloud: 'https://soundcloud.com/room-haus/mx008-big-chain',
    audioSourceURL: `${BASE_URL}MX008/MX008.m3u8`,
  },
  {
    id: 'MX009',
    art: art.MX009,
    label: labels.MX009,
    name: 'Music for Rain',
    artist: 'Sami',
    catalogueNumber: 'MX009',
    soundcloud: 'https://soundcloud.com/room-haus/mx009-sami',
    audioSourceURL: `${BASE_URL}MX009/MX009.m3u8`,
  },
  {
    id: 'MX010',
    art: art.MX010,
    label: labels.MX010,
    name: 'For Consumption',
    artist: 'Harry',
    catalogueNumber: 'MX010',
    soundcloud: 'https://soundcloud.com/room-haus/mx010-harry',
    audioSourceURL: `${BASE_URL}MX010/MX010.m3u8`,
  },
  {
    id: 'MX011',
    art: art.MX011,
    label: labels.MX011,
    artist: 'KLM',
    catalogueNumber: 'MX011',
    soundcloud: 'https://soundcloud.com/room-haus/mx011-klm',
    audioSourceURL: `${BASE_URL}MX011/MX011.m3u8`,
  },
  {
    id: 'MX012',
    art: art.MX012,
    label: labels.MX012,
    name: 'Jersey Edition',
    artist: 'Rawle Night Long',
    catalogueNumber: 'MX012',
    soundcloud: 'https://soundcloud.com/room-haus/mx012-rawle-night-long',
    audioSourceURL: `${BASE_URL}MX012/MX012.m3u8`,
  },
  {
    id: 'MX013',
    art: art.MX013,
    label: labels.MX013,
    name: 'Acid Club',
    artist: '35mm & Iwan Thickett',
    catalogueNumber: 'MX013',
    soundcloud: 'https://soundcloud.com/room-haus/mx013-acid-club',
    audioSourceURL: `${BASE_URL}MX013/MX013.m3u8`,
  },
  {
    id: 'MX014',
    art: art.MX014,
    label: labels.MX014,
    name: 'A LOVE LETTER 2 SOUNDCLOUD',
    artist: 'Mr. Fade',
    catalogueNumber: 'MX014',
    soundcloud: 'https://soundcloud.com/room-haus/mx014-mr-fade',
    audioSourceURL: `${BASE_URL}MX014/MX014.m3u8`,
  },
  {
    id: 'MX015',
    art: art.MX015,
    label: labels.MX015,
    artist: 'Iwan Thickett',
    catalogueNumber: 'MX015',
    soundcloud: 'https://soundcloud.com/room-haus/mx015-iwan-thickett',
    audioSourceURL: `${BASE_URL}MX015/MX015.m3u8`,
  },
  {
    id: 'MX016',
    art: art.MX016,
    label: labels.MX016,
    name: 'Mirage Mix',
    artist: 'Fady D',
    catalogueNumber: 'MX016',
    soundcloud: 'https://soundcloud.com/room-haus/mx016-fady-d',
    audioSourceURL: `${BASE_URL}MX016/MX016.m3u8`,
  },
  {
    id: 'MX017',
    art: art.MX017,
    label: labels.MX017,
    name: 'Winter Headflex',
    artist: 'DJ Swingling',
    catalogueNumber: 'MX017',
    soundcloud: 'https://soundcloud.com/room-haus/mx017-dj-swingline',
    audioSourceURL: `${BASE_URL}MX017/MX017.m3u8`,
  },
  {
    id: 'MX018',
    art: art.MX018,
    label: labels.MX018,
    name: 'Final Words',
    artist: 'Jett Chandon',
    catalogueNumber: 'MX018',
    soundcloud: 'https://soundcloud.com/room-haus/mx018-jett-chandon',
    audioSourceURL: `${BASE_URL}MX018/MX018.m3u8`,
  },
  {
    id: 'MX019',
    art: art.MX019,
    label: labels.MX019,
    name: 'Angel Of The Extinct Heart',
    artist: 'Tony Cruise',
    catalogueNumber: 'MX019',
    soundcloud: 'https://soundcloud.com/room-haus/mx019-tony-cruise',
    audioSourceURL: `${BASE_URL}MX019/MX019.m3u8`,
  },
  {
    id: 'MX020',
    art: art.MX020,
    label: labels.MX020,
    artist: 'Chadwick',
    catalogueNumber: 'MX020',
    soundcloud: 'https://soundcloud.com/room-haus/mx020-chadwick',
    audioSourceURL: `${BASE_URL}MX020/MX020.m3u8`,
  },
  {
    id: 'MX021',
    art: art.MX021,
    label: labels.MX021,
    artist: 'Tooth Choir',
    name: 'Falter',
    catalogueNumber: 'MX021',
    soundcloud: 'https://soundcloud.com/room-haus/mx021-tooth-choir',
    audioSourceURL: `${BASE_URL}MX021/MX021.m3u8`,
  },
  {
    id: 'MX022',
    art: art.MX022,
    label: labels.MX022,
    artist: 'Nick Garcia',
    name: 'Test Of Time',
    catalogueNumber: 'MX022',
    soundcloud: 'https://soundcloud.com/room-haus/mx022-nick-garcia',
    audioSourceURL: `${BASE_URL}MX022/MX022.m3u8`,
  },
  {
    id: 'MX023',
    art: art.MX023,
    label: labels.MX023,
    artist: 'Ayesha',
    name: 'Does It Bring You Joy',
    catalogueNumber: 'MX023',
    soundcloud: 'https://soundcloud.com/room-haus/mx023-ayesha',
    audioSourceURL: `${BASE_URL}MX023/MX023.m3u8`,
  },
  {
    id: 'MX024',
    art: art.MX024,
    label: labels.MX024,
    artist: 'Hipster Woods',
    name: 'Banned POC',
    catalogueNumber: 'MX024',
    soundcloud: 'https://soundcloud.com/room-haus/mx024-hipster-woods',
    audioSourceURL: `${BASE_URL}MX024/MX024.m3u8`,
  },
  {
    id: 'MX025',
    art: art.MX025,
    label: labels.MX025,
    artist: 'Michael The Lion B2B Shawn Ryan',
    name: 'Funk Train DC',
    catalogueNumber: 'MX025',
    soundcloud: 'https://soundcloud.com/room-haus/mx025-michael-the-lion-b2b-shawn-ryan',
    audioSourceURL: `${BASE_URL}MX025/MX025.m3u8`,
  },
  {
    id: 'MX026',
    art: art.MX026,
    label: labels.MX026,
    artist: 'AC Rowland',
    catalogueNumber: 'MX026',
    soundcloud: 'https://soundcloud.com/room-haus/mx026-ac-rowland',
    audioSourceURL: `${BASE_URL}MX026/MX026.m3u8`,
  },
  {
    id: 'MX027',
    art: art.MX027,
    label: labels.MX027,
    artist: 'DJ Nativesun',
    name: 'Swing That',
    catalogueNumber: 'MX027',
    soundcloud: 'https://soundcloud.com/room-haus/mx027-dj-nativesun',
    audioSourceURL: `${BASE_URL}MX027/MX027.m3u8`,
  },
  {
    id: 'MX028',
    art: art.MX028,
    label: labels.MX028,
    artist: 'Naygod',
    name: 'Deconstructed',
    catalogueNumber: 'MX028',
    soundcloud: 'https://soundcloud.com/room-haus/mx028-naygod',
    audioSourceURL: `${BASE_URL}MX028/MX028.m3u8`,
  },
  {
    id: 'MX029',
    art: art.MX029,
    label: labels.MX029,
    artist: 'Saad Ashraf',
    name: 'Settle Another Day',
    catalogueNumber: 'MX029',
    soundcloud: 'https://soundcloud.com/room-haus/mx029-saad-ashraf',
    audioSourceURL: `${BASE_URL}MX029/audio/MX029.m3u8`,
  },
  {
    id: 'MX030',
    art: art.MX030,
    label: labels.MX030,
    artist: 'ART DLR',
    name: 'W4',
    catalogueNumber: 'MX030',
    soundcloud: 'https://soundcloud.com/room-haus/mx030-art-dlr',
    audioSourceURL: `${BASE_URL}MX030/MX030.m3u8`,
  },
  {
    id: 'MX031',
    art: art.MX031,
    label: labels.MX031,
    artist: 'PC Pete',
    name: 'Farther Along',
    catalogueNumber: 'MX031',
    soundcloud: 'https://soundcloud.com/room-haus/mx031-pcpete',
    audioSourceURL: `${BASE_URL}MX031/MX031.m3u8`,
  },
  {
    id: 'MX032',
    art: art.MX032,
    label: labels.MX032,
    artist: 'GABBERBITCH69',
    name: 'No Te Acerques A Mí',
    catalogueNumber: 'MX032',
    soundcloud: 'https://soundcloud.com/room-haus/mx032-gabberbitch69',
    audioSourceURL: `${BASE_URL}MX032/MX032.m3u8`,
  },
  {
    id: 'MX033',
    art: art.MX033,
    label: labels.MX033,
    artist: 'Outputmessage',
    name: 'The Octopus Room',
    catalogueNumber: 'MX033',
    soundcloud: 'https://soundcloud.com/room-haus/mx033-outputmessage',
    audioSourceURL: `${BASE_URL}MX033/MX033.m3u8`,
  },
  {
    id: 'MX034',
    art: art.MX034,
    label: labels.MX034,
    artist: 'Kenny M',
    name: 'Post-Coital Funk',
    catalogueNumber: 'MX034',
    soundcloud: 'https://soundcloud.com/room-haus/mx034-kenny-m',
    audioSourceURL: `${BASE_URL}MX034/MX034.m3u8`,
  },
  {
    id: 'MX035',
    art: art.MX035,
    label: labels.MX035,
    artist: 'Tony G',
    name: 'Global Warning',
    catalogueNumber: 'MX035',
    soundcloud: 'https://soundcloud.com/room-haus/mx035-tony-g',
    audioSourceURL: `${BASE_URL}MX035/MX035.m3u8`,
  },
  {
    id: 'MX036',
    art: art.MX036,
    label: labels.MX036,
    artist: 'DJ Land Reform',
    name: 'Make It Hot',
    catalogueNumber: 'MX036',
    soundcloud: 'https://soundcloud.com/room-haus/mx036-dj-land-reform',
    audioSourceURL: `${BASE_URL}MX036/MX036.m3u8`,
  },
  {
    id: 'MX037',
    art: art.MX037,
    label: labels.MX037,
    artist: '35mm',
    name: 'Unwanted Unneeded',
    catalogueNumber: 'MX037',
    soundcloud: 'https://soundcloud.com/room-haus/mx037-35mm',
    audioSourceURL: `${BASE_URL}MX037/MX037.m3u8`,
  },
  {
    id: 'MX038',
    art: art.MX038,
    label: labels.MX038,
    artist: 'Blindstares B2B Noce',
    name: 'Good & Plenty',
    catalogueNumber: 'MX038',
    soundcloud: 'https://soundcloud.com/room-haus/mx038-blindstares-b2b-noce',
    audioSourceURL: `${BASE_URL}MX038/MX038.m3u8`,
  },
  {
    id: 'MX039',
    art: art.MX039,
    label: labels.MX039,
    artist: 'Naíome',
    catalogueNumber: 'MX039',
    soundcloud: 'https://soundcloud.com/room-haus/mx039-naiome',
    audioSourceURL: `${BASE_URL}MX039/MX039.m3u8`,
  },
  {
    id: 'MX040',
    art: art.MX040,
    label: labels.MX040,
    artist: 'Jamel Zuñiga',
    name: 'Violence Jack',
    catalogueNumber: 'MX040',
    soundcloud: 'https://soundcloud.com/room-haus/mx040-jamel-zuniga',
    audioSourceURL: `${BASE_URL}MX040/MX040.m3u8`,
  },
  {
    id: 'MX041',
    art: art.MX041,
    label: labels.MX041,
    artist: 'Rose Corps',
    name: 'Late Night Summer Feels',
    catalogueNumber: 'MX041',
    soundcloud: 'https://soundcloud.com/room-haus/mx041-rose-corps',
    audioSourceURL: `${BASE_URL}MX041/MX041.m3u8`,
  },
  {
    id: 'MX042',
    art: art.MX042,
    label: labels.MX042,
    artist: 'Saintgolder',
    catalogueNumber: 'MX042',
    soundcloud: 'https://soundcloud.com/room-haus/mx042-saintgolder',
    audioSourceURL: `${BASE_URL}MX042/MX042.m3u8`,
  },
  {
    id: 'MX043',
    art: art.MX043,
    label: labels.MX043,
    artist: 'Kundalini',
    name: 'T÷MPL÷12',
    catalogueNumber: 'MX043',
    soundcloud: 'https://soundcloud.com/room-haus/mx043-kundalini',
    audioSourceURL: `${BASE_URL}MX043/MX043.m3u8`,
  },
  {
    id: 'MX044',
    art: art.MX044,
    label: labels.MX044,
    artist: 'Sofia Lakis',
    name: 'Slamdancer',
    catalogueNumber: 'MX044',
    soundcloud: 'https://soundcloud.com/room-haus/mx044-sofia-lakis',
    audioSourceURL: `${BASE_URL}MX044/MX044.m3u8`,
  },
  {
    id: 'MX045',
    art: art.MX045,
    label: labels.MX045,
    artist: 'Rush Midnight',
    catalogueNumber: 'MX045',
    soundcloud: 'https://soundcloud.com/room-haus/mx045-rush-midnight',
    audioSourceURL: `${BASE_URL}MX045/MX045.m3u8`,
  },
  {
    id: 'MX046',
    art: art.MX046,
    label: labels.MX046,
    artist: "L'ENFANT",
    catalogueNumber: 'MX046',
    soundcloud: 'https://soundcloud.com/room-haus/mx046-lenfant',
    audioSourceURL: `${BASE_URL}MX046/MX046.m3u8`,
  },
  {
    id: 'MX047',
    art: art.MX047,
    label: labels.MX047,
    artist: 'Baronhawk Poitier',
    name: "Smedium Sweat Smix 99'19",
    catalogueNumber: 'MX047',
    soundcloud: 'https://soundcloud.com/room-haus/mx047-baronhawk-poitier',
    audioSourceURL: `${BASE_URL}MX047/MX047.m3u8`,
  },
  // {
  //   id: 'MX048',
  //   art: art.MX048,
  //   label: labels.MX048,
  //   artist: 'Furtive',
  //   name: "Furtive's Woozy Twilight Retreating Star Haze",
  //   catalogueNumber: 'MX048',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx048-furtive',
  //   audioSourceURL: `${BASE_URL}MX048/MX048.m3u8`,
  // },
  // {
  //   id: 'MX049',
  //   art: art.MX049,
  //   label: labels.MX049,
  //   artist: 'Metal Femme',
  //   name: 'Fling Flames From Her 6 Million Arms',
  //   catalogueNumber: 'MX049',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx049-metal-femme',
  //   audioSourceURL: `${BASE_URL}MX049/MX049.m3u8`,
  // },
  // {
  //   id: 'MX050',
  //   art: art.MX050,
  //   label: labels.MX050,
  //   artist: 'Sifu Sun',
  //   name: 'Oops',
  //   catalogueNumber: 'MX050',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx050-sifu-sun',
  //   audioSourceURL: `${BASE_URL}MX050/MX050.m3u8`,
  // },
  // {
  //   id: 'MX051',
  //   art: art.MX051,
  //   label: labels.MX051,
  //   artist: 'Amal',
  //   name: 'The Stigg (Free Jugg)',
  //   catalogueNumber: 'MX051',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx051-amal',
  //   audioSourceURL: `${BASE_URL}MX051/MX051.m3u8`,
  // },
  // {
  //   id: 'MX052',
  //   art: art.MX052,
  //   label: labels.MX052,
  //   artist: 'Obsidian',
  //   name: 'Geode',
  //   catalogueNumber: 'MX052',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx052-obsid1an',
  //   audioSourceURL: `${BASE_URL}MX052/MX052.m3u8`,
  // },
  // {
  //   id: 'MX053',
  //   art: art.MX053,
  //   label: labels.MX053,
  //   artist: 'Panch',
  //   catalogueNumber: 'MX053',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx053-panch',
  //   audioSourceURL: `${BASE_URL}MX053/MX053.m3u8`,
  // },
  // {
  //   id: 'MX054',
  //   art: art.MX054,
  //   label: labels.MX054,
  //   artist: 'Jamie',
  //   catalogueNumber: 'MX054',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx054-jamie',
  //   audioSourceURL: `${BASE_URL}MX054/MX054.m3u8`,
  // },
  // {
  //   id: 'MX055',
  //   art: art.MX055,
  //   label: labels.MX055,
  //   artist: 'Nocturnal Wax',
  //   name: 'Welcome To the Jungle',
  //   catalogueNumber: 'MX055',
  //   soundcloud: 'https://soundcloud.com/room-haus/mx055-nocturnal-wax',
  //   audioSourceURL: `${BASE_URL}MX055/MX055.m3u8`,
  // },
  //   id: 'RM001',
  //   art: rm001,
  //   artist: 'Tony Cruise',
  //   name: 'Only Consensual',
  //   catalogueNumber: 'ROOM001',
  //   hidden: true,
  // },
];

export const getMix = (mx) => mixes.find((mix) => mx === mix.id);
