import * as art from 'src/images/mix-art/';
import rm001 from '../images/rm001.jpg';

export const mixes = [
  {
    id: 'MX001',
    art: art.MX001,
    artist: 'Eddy Bauer',
    catalogueNumber: 'MX001',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx001-eddy-bauer',
  },
  {
    id: 'MX002',
    art: art.MX002,
    artist: '35mm',
    catalogueNumber: 'MX002',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx002-35mm',
  },
  {
    id: 'MX003',
    art: art.MX003,
    artist: 'Blackfoot Millie',
    catalogueNumber: 'MX003',
    soundcloud: 'https://soundcloud.com/room-haus/mx003-blackfoot-millie-live',
  },
  {
    id: 'MX004',
    art: art.MX004,
    artist: 'Iwan Thickett',
    name: 'MX004: Iwan Thickett',
    catalogueNumber: 'MX004',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx004-iwan-thickett',
  },
  {
    id: 'MX005',
    art: art.MX005,
    artist: 'AV',
    catalogueNumber: 'MX005',
    soundcloud: 'https://soundcloud.com/room-haus/mx005-av',
  },
  {
    id: 'MX006',
    art: art.MX006,
    catalogueNumber: 'MX006',
    artist: 'Articil',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx006-articil',
  },
  {
    id: 'MX007',
    art: art.MX007,
    artist: 'Wade Hammes',
    catalogueNumber: 'MX007',
    soundcloud: 'https://soundcloud.com/room-haus/mx007-wade-hammes',
  },
  {
    id: 'MX008',
    art: art.MX008,
    artist: 'Big Chain',
    catalogueNumber: 'MX008',
    soundcloud: 'https://soundcloud.com/room-haus/mx008-big-chain',
  },
  {
    id: 'MX009',
    art: art.MX009,
    name: 'Music for Rain',
    artist: 'Sami',
    catalogueNumber: 'MX009',
    soundcloud: 'https://soundcloud.com/room-haus/mx009-sami',
  },
  {
    id: 'MX010',
    art: art.MX010,
    name: 'For Consumption',
    artist: 'Harry',
    catalogueNumber: 'MX010',
    soundcloud: 'https://soundcloud.com/room-haus/mx010-harry',
  },
  {
    id: 'MX011',
    art: art.MX011,
    artist: 'KLM',
    catalogueNumber: 'MX011',
    soundcloud: 'https://soundcloud.com/room-haus/mx011-klm',
  },
  {
    id: 'MX012',
    art: art.MX012,
    name: 'Jersey Edition',
    artist: 'Rawle Night Long',
    catalogueNumber: 'MX012',
    soundcloud: 'https://soundcloud.com/room-haus/mx012-rawle-night-long',
  },
  {
    id: 'MX013',
    art: art.MX013,
    name: 'Acid Club',
    artist: '35mm & Iwan Thickett',
    catalogueNumber: 'MX013',
    soundcloud: 'https://soundcloud.com/room-haus/mx013-acid-club',
  },
  {
    id: 'MX014',
    art: art.MX014,
    name: 'A LOVE LETTER 2 SOUNDCLOUD',
    artist: 'Mr. Fade',
    catalogueNumber: 'MX014',
    soundcloud: 'https://soundcloud.com/room-haus/mx014-mr-fade',
  },
  {
    id: 'MX015',
    art: art.MX015,
    artist: 'Iwan Thickett',
    catalogueNumber: 'MX015',
    soundcloud: 'https://soundcloud.com/room-haus/mx015-iwan-thickett',
  },
  {
    id: 'MX016',
    art: art.MX016,
    name: 'Mirage Mix',
    artist: 'Fady D',
    catalogueNumber: 'MX016',
    soundcloud: 'https://soundcloud.com/room-haus/mx016-fady-d',
  },
  {
    id: 'MX017',
    art: art.MX017,
    name: 'Winter Headflex',
    artist: 'DJ Swingling',
    catalogueNumber: 'MX017',
    soundcloud: 'https://soundcloud.com/room-haus/mx017-dj-swingline',
  },
  {
    id: 'MX018',
    art: art.MX018,
    name: 'Final Words',
    artist: 'Jett Chandon',
    catalogueNumber: 'MX018',
    soundcloud: 'https://soundcloud.com/room-haus/mx018-jett-chandon',
  },
  {
    id: 'MX019',
    art: art.MX019,
    name: 'Angel Of The Extinct Heart',
    artist: 'Tony Cruise',
    catalogueNumber: 'MX019',
    soundcloud: 'https://soundcloud.com/room-haus/mx019-tony-cruise',
  },
  {
    id: 'MX020',
    art: art.MX020,
    artist: 'Chadwick',
    catalogueNumber: 'MX020',
    soundcloud: 'https://soundcloud.com/room-haus/mx020-chadwick',
  },
  {
    id: 'MX021',
    art: art.MX021,
    artist: 'Tooth Choir',
    name: 'Falter',
    catalogueNumber: 'MX021',
    soundcloud: 'https://soundcloud.com/room-haus/mx021-tooth-choir',
  },
  {
    id: 'MX022',
    art: art.MX022,
    artist: 'Nick Garcia',
    name: 'Test Of Time',
    catalogueNumber: 'MX022',
    soundcloud: 'https://soundcloud.com/room-haus/mx022-nick-garcia',
  },
  {
    id: 'MX023',
    art: art.MX023,
    artist: 'Ayesha',
    name: 'Does It Bring You Joy',
    catalogueNumber: 'MX023',
    soundcloud: 'https://soundcloud.com/room-haus/mx023-ayesha',
  },
  {
    id: 'MX024',
    art: art.MX024,
    artist: 'Hipster Woods',
    name: 'Banned POC',
    catalogueNumber: 'MX024',
    soundcloud: 'https://soundcloud.com/room-haus/mx024-hipster-woods',
  },
  {
    id: 'MX025',
    art: art.MX025,
    artist: 'Michael The Lion B2B Shawn Ryan',
    name: 'Funk Train DC',
    catalogueNumber: 'MX025',
    soundcloud: 'https://soundcloud.com/room-haus/mx025-michael-the-lion-b2b-shawn-ryan',
  },
  {
    id: 'MX026',
    art: art.MX026,
    artist: 'AC Rowland',
    catalogueNumber: 'MX026',
    soundcloud: 'https://soundcloud.com/room-haus/mx026-ac-rowland',
  },
  {
    id: 'MX027',
    art: art.MX027,
    artist: 'DJ Nativesun',
    name: 'Swing That',
    catalogueNumber: 'MX027',
    soundcloud: 'https://soundcloud.com/room-haus/mx027-dj-nativesun',
  },
  {
    id: 'MX028',
    art: art.MX028,
    artist: 'Naygod',
    name: 'Deconstructed',
    catalogueNumber: 'MX028',
    soundcloud: 'https://soundcloud.com/room-haus/mx028-naygod',
  },
  {
    id: 'MX029',
    art: art.MX029,
    artist: 'Saad Ashraf',
    name: 'Settle Another Day',
    catalogueNumber: 'MX029',
    soundcloud: 'https://soundcloud.com/room-haus/mx029-saad-ashraf',
  },
  {
    id: 'MX030',
    art: art.MX030,
    artist: 'ART DLR',
    name: 'W4',
    catalogueNumber: 'MX030',
    soundcloud: 'https://soundcloud.com/room-haus/mx030-art-dlr',
  },
  {
    id: 'MX031',
    art: art.MX031,
    artist: 'PC Pete',
    name: 'Farther Along',
    catalogueNumber: 'MX031',
    soundcloud: 'https://soundcloud.com/room-haus/mx031-pcpete',
  },
  {
    id: 'MX032',
    art: art.MX032,
    artist: 'GABBERBITCH69',
    name: 'No Te Acerques A Mí',
    catalogueNumber: 'MX032',
    soundcloud: 'https://soundcloud.com/room-haus/mx032-gabberbitch69',
  },
  {
    id: 'MX033',
    art: art.MX033,
    artist: 'Outputmessage',
    name: 'The Octopus Room',
    catalogueNumber: 'MX033',
    soundcloud: 'https://soundcloud.com/room-haus/mx033-outputmessage',
  },
  {
    id: 'MX034',
    art: art.MX034,
    artist: 'Kenny M',
    name: 'Post-Coital Funk',
    catalogueNumber: 'MX034',
    soundcloud: 'https://soundcloud.com/room-haus/mx034-kenny-m',
  },
  {
    id: 'MX035',
    art: art.MX035,
    artist: 'Tony G',
    name: 'Global Warning',
    catalogueNumber: 'MX035',
    soundcloud: 'https://soundcloud.com/room-haus/mx035-tony-g',
  },
  {
    id: 'MX036',
    art: art.MX036,
    artist: 'DJ Land Reform',
    name: 'Make It Hot',
    catalogueNumber: 'MX036',
    soundcloud: 'https://soundcloud.com/room-haus/mx036-dj-land-reform',
  },
  //   id: 'RM001',
  //   art: rm001,
  //   artist: 'Tony Cruise',
  //   name: 'Only Consensual',
  //   catalogueNumber: 'ROOM001',
  //   hidden: true,
  // },
];

export const getMix = (mx) => mixes.find((mix) => mx === mix.id);

export const liveMixes = mixes.filter((mx) => !mx.hidden);
