import * as art from 'src/images/mix-art/';
// import rm001 from '../images/rm001.jpg';

const BASE_URL = 'https://roomhauscdnprd.blob.core.windows.net/mixes/';

export const mixes = [
  {
    id: 'MX001',
    art: art.MX001,
    artist: 'Eddy Bauer',
    catalogueNumber: 'MX001',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx001-eddy-bauer',
    audioSourceURL: `${BASE_URL}MX001/MX001.m3u8`,
  },
  {
    id: 'MX002',
    art: art.MX002,
    artist: '35mm',
    catalogueNumber: 'MX002',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx002-35mm',
    audioSourceURL: `${BASE_URL}MX002/MX002.m3u8`,
  },
  {
    id: 'MX003',
    art: art.MX003,
    artist: 'Blackfoot Millie',
    catalogueNumber: 'MX003',
    soundcloud: 'https://soundcloud.com/room-haus/mx003-blackfoot-millie-live',
    audioSourceURL: `${BASE_URL}MX003/MX003.m3u8`,
  },
  {
    id: 'MX004',
    art: art.MX004,
    artist: 'Iwan Thickett',
    name: 'MX004: Iwan Thickett',
    catalogueNumber: 'MX004',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx004-iwan-thickett',
    audioSourceURL: `${BASE_URL}MX004/MX004.m3u8`,
  },
  {
    id: 'MX005',
    art: art.MX005,
    artist: 'AV',
    catalogueNumber: 'MX005',
    soundcloud: 'https://soundcloud.com/room-haus/mx005-av',
    audioSourceURL: `${BASE_URL}MX005/MX005.m3u8`,
  },
  {
    id: 'MX006',
    art: art.MX006,
    catalogueNumber: 'MX006',
    artist: 'Articil',
    soundcloud: 'https://soundcloud.com/room-haus/room-mx006-articil',
    audioSourceURL: `${BASE_URL}MX006/MX006.m3u8`,
  },
  {
    id: 'MX007',
    art: art.MX007,
    artist: 'Wade Hammes',
    catalogueNumber: 'MX007',
    soundcloud: 'https://soundcloud.com/room-haus/mx007-wade-hammes',
    audioSourceURL: `${BASE_URL}MX007/MX007.m3u8`,
  },
  {
    id: 'MX008',
    art: art.MX008,
    artist: 'Big Chain',
    catalogueNumber: 'MX008',
    soundcloud: 'https://soundcloud.com/room-haus/mx008-big-chain',
    audioSourceURL: `${BASE_URL}MX008/MX008.m3u8`,
  },
  {
    id: 'MX009',
    art: art.MX009,
    name: 'Music for Rain',
    artist: 'Sami',
    catalogueNumber: 'MX009',
    soundcloud: 'https://soundcloud.com/room-haus/mx009-sami',
    audioSourceURL: `${BASE_URL}MX009/MX009.m3u8`,
  },
  {
    id: 'MX010',
    art: art.MX010,
    name: 'For Consumption',
    artist: 'Harry',
    catalogueNumber: 'MX010',
    soundcloud: 'https://soundcloud.com/room-haus/mx010-harry',
    audioSourceURL: `${BASE_URL}MX010/MX010.m3u8`,
  },
  {
    id: 'MX011',
    art: art.MX011,
    artist: 'KLM',
    catalogueNumber: 'MX011',
    soundcloud: 'https://soundcloud.com/room-haus/mx011-klm',
    audioSourceURL: `${BASE_URL}MX011/MX011.m3u8`,
  },
  {
    id: 'MX012',
    art: art.MX012,
    name: 'Jersey Edition',
    artist: 'Rawle Night Long',
    catalogueNumber: 'MX012',
    soundcloud: 'https://soundcloud.com/room-haus/mx012-rawle-night-long',
    audioSourceURL: `${BASE_URL}MX012/MX012.m3u8`,
  },
  {
    id: 'MX013',
    art: art.MX013,
    name: 'Acid Club',
    artist: '35mm & Iwan Thickett',
    catalogueNumber: 'MX013',
    soundcloud: 'https://soundcloud.com/room-haus/mx013-acid-club',
    audioSourceURL: `${BASE_URL}MX013/MX013.m3u8`,
  },
  {
    id: 'MX014',
    art: art.MX014,
    name: 'A LOVE LETTER 2 SOUNDCLOUD',
    artist: 'Mr. Fade',
    catalogueNumber: 'MX014',
    soundcloud: 'https://soundcloud.com/room-haus/mx014-mr-fade',
    audioSourceURL: `${BASE_URL}MX014/MX014.m3u8`,
  },
  {
    id: 'MX015',
    art: art.MX015,
    artist: 'Iwan Thickett',
    catalogueNumber: 'MX015',
    soundcloud: 'https://soundcloud.com/room-haus/mx015-iwan-thickett',
    audioSourceURL: `${BASE_URL}MX015/MX015.m3u8`,
  },
  {
    id: 'MX016',
    art: art.MX016,
    name: 'Mirage Mix',
    artist: 'Fady D',
    catalogueNumber: 'MX016',
    soundcloud: 'https://soundcloud.com/room-haus/mx016-fady-d',
    audioSourceURL: `${BASE_URL}MX016/MX016.m3u8`,
  },
  {
    id: 'MX017',
    art: art.MX017,
    name: 'Winter Headflex',
    artist: 'DJ Swingling',
    catalogueNumber: 'MX017',
    soundcloud: 'https://soundcloud.com/room-haus/mx017-dj-swingline',
    audioSourceURL: `${BASE_URL}MX017/MX017.m3u8`,
  },
  {
    id: 'MX018',
    art: art.MX018,
    name: 'Final Words',
    artist: 'Jett Chandon',
    catalogueNumber: 'MX018',
    soundcloud: 'https://soundcloud.com/room-haus/mx018-jett-chandon',
    audioSourceURL: `${BASE_URL}MX018/MX018.m3u8`,
  },
  {
    id: 'MX019',
    art: art.MX019,
    name: 'Angel Of The Extinct Heart',
    artist: 'Tony Cruise',
    catalogueNumber: 'MX019',
    soundcloud: 'https://soundcloud.com/room-haus/mx019-tony-cruise',
    audioSourceURL: `${BASE_URL}MX019/MX019.m3u8`,
  },
  {
    id: 'MX020',
    art: art.MX020,
    artist: 'Chadwick',
    catalogueNumber: 'MX020',
    soundcloud: 'https://soundcloud.com/room-haus/mx020-chadwick',
    audioSourceURL: `${BASE_URL}MX020/MX020.m3u8`,
  },
  {
    id: 'MX021',
    art: art.MX021,
    artist: 'Tooth Choir',
    name: 'Falter',
    catalogueNumber: 'MX021',
    soundcloud: 'https://soundcloud.com/room-haus/mx021-tooth-choir',
    audioSourceURL: `${BASE_URL}MX021/MX021.m3u8`,
  },
  {
    id: 'MX022',
    art: art.MX022,
    artist: 'Nick Garcia',
    name: 'Test Of Time',
    catalogueNumber: 'MX022',
    soundcloud: 'https://soundcloud.com/room-haus/mx022-nick-garcia',
    audioSourceURL: `${BASE_URL}MX022/MX022.m3u8`,
  },
  {
    id: 'MX023',
    art: art.MX023,
    artist: 'Ayesha',
    name: 'Does It Bring You Joy',
    catalogueNumber: 'MX023',
    soundcloud: 'https://soundcloud.com/room-haus/mx023-ayesha',
    audioSourceURL: `${BASE_URL}MX023/MX023.m3u8`,
  },
  {
    id: 'MX024',
    art: art.MX024,
    artist: 'Hipster Woods',
    name: 'Banned POC',
    catalogueNumber: 'MX024',
    soundcloud: 'https://soundcloud.com/room-haus/mx024-hipster-woods',
    audioSourceURL: `${BASE_URL}MX024/MX024.m3u8`,
  },
  {
    id: 'MX025',
    art: art.MX025,
    artist: 'Michael The Lion B2B Shawn Ryan',
    name: 'Funk Train DC',
    catalogueNumber: 'MX025',
    soundcloud: 'https://soundcloud.com/room-haus/mx025-michael-the-lion-b2b-shawn-ryan',
    audioSourceURL: `${BASE_URL}MX025/MX025.m3u8`,
  },
  {
    id: 'MX026',
    art: art.MX026,
    artist: 'AC Rowland',
    catalogueNumber: 'MX026',
    soundcloud: 'https://soundcloud.com/room-haus/mx026-ac-rowland',
    audioSourceURL: `${BASE_URL}MX026/MX026.m3u8`,
  },
  {
    id: 'MX027',
    art: art.MX027,
    artist: 'DJ Nativesun',
    name: 'Swing That',
    catalogueNumber: 'MX027',
    soundcloud: 'https://soundcloud.com/room-haus/mx027-dj-nativesun',
    audioSourceURL: `${BASE_URL}MX027/MX027.m3u8`,
  },
  {
    id: 'MX028',
    art: art.MX028,
    artist: 'Naygod',
    name: 'Deconstructed',
    catalogueNumber: 'MX028',
    soundcloud: 'https://soundcloud.com/room-haus/mx028-naygod',
    audioSourceURL: `${BASE_URL}MX028/MX028.m3u8`,
  },
  {
    id: 'MX029',
    art: art.MX029,
    artist: 'Saad Ashraf',
    name: 'Settle Another Day',
    catalogueNumber: 'MX029',
    soundcloud: 'https://soundcloud.com/room-haus/mx029-saad-ashraf',
    audioSourceURL: `${BASE_URL}MX029/audio/MX029.m3u8`,
  },
  {
    id: 'MX030',
    art: art.MX030,
    artist: 'ART DLR',
    name: 'W4',
    catalogueNumber: 'MX030',
    soundcloud: 'https://soundcloud.com/room-haus/mx030-art-dlr',
    audioSourceURL: `${BASE_URL}MX030/MX030.m3u8`,
  },
  {
    id: 'MX031',
    art: art.MX031,
    artist: 'PC Pete',
    name: 'Farther Along',
    catalogueNumber: 'MX031',
    soundcloud: 'https://soundcloud.com/room-haus/mx031-pcpete',
    audioSourceURL: `${BASE_URL}MX031/MX031.m3u8`,
  },
  {
    id: 'MX032',
    art: art.MX032,
    artist: 'GABBERBITCH69',
    name: 'No Te Acerques A Mí',
    catalogueNumber: 'MX032',
    soundcloud: 'https://soundcloud.com/room-haus/mx032-gabberbitch69',
    audioSourceURL: `${BASE_URL}MX032/MX032.m3u8`,
  },
  {
    id: 'MX033',
    art: art.MX033,
    artist: 'Outputmessage',
    name: 'The Octopus Room',
    catalogueNumber: 'MX033',
    soundcloud: 'https://soundcloud.com/room-haus/mx033-outputmessage',
    audioSourceURL: `${BASE_URL}MX033/MX033.m3u8`,
  },
  {
    id: 'MX034',
    art: art.MX034,
    artist: 'Kenny M',
    name: 'Post-Coital Funk',
    catalogueNumber: 'MX034',
    soundcloud: 'https://soundcloud.com/room-haus/mx034-kenny-m',
    audioSourceURL: `${BASE_URL}MX034/MX034.m3u8`,
  },
  {
    id: 'MX035',
    art: art.MX035,
    artist: 'Tony G',
    name: 'Global Warning',
    catalogueNumber: 'MX035',
    soundcloud: 'https://soundcloud.com/room-haus/mx035-tony-g',
    audioSourceURL: `${BASE_URL}MX035/MX035.m3u8`,
  },
  {
    id: 'MX036',
    art: art.MX036,
    artist: 'DJ Land Reform',
    name: 'Make It Hot',
    catalogueNumber: 'MX036',
    soundcloud: 'https://soundcloud.com/room-haus/mx036-dj-land-reform',
    audioSourceURL: `${BASE_URL}MX036/MX036.m3u8`,
  },
  {
    id: 'MX037',
    art: art.MX037,
    artist: '35mm',
    name: 'Unwanted Unneeded',
    catalogueNumber: 'MX037',
    soundcloud: 'https://soundcloud.com/room-haus/mx037-35mm',
    audioSourceURL: `${BASE_URL}MX037/MX037.m3u8`,
  },
  {
    id: 'MX038',
    art: art.MX038,
    artist: 'Blindstares b2b Noce',
    name: 'Good & Plenty',
    catalogueNumber: 'MX038',
    soundcloud: 'https://soundcloud.com/room-haus/mx038-blindstares-b2b-noce',
    audioSourceURL: `${BASE_URL}MX037/MX037.m3u8`,
  },
  //   id: 'RM001',
  //   art: rm001,
  //   artist: 'Tony Cruise',
  //   name: 'Only Consensual',
  //   catalogueNumber: 'ROOM001',
  //   hidden: true,
  // },
];

export const getMix = (mx) => mixes.find((mix) => mx === mix.id);

export const liveMixes = mixes.filter((mx) => !mx.hidden);
